orcamentos/app/urls.py
from django.urls import path
from .views import cliente_views, orcamento_views, funcionario_views, autenticacao_views

urlpatterns = [
    path('cadastrar_cliente', cliente_views.cadastrar_cliente, name='cadastrar_cliente'),
    path('listar_clientes', cliente_views.listar_clientes, name='listar_clientes'),
    path('lista_cliente/<int:id>', cliente_views.listar_cliente_id, name='listar_cliente_id'),
    path('editar_cliente/<int:id>', cliente_views.editar_cliente, name='editar_cliente'),
    path('editar_orcamento/<int:id>', orcamento_views.editar_orcamento, name='editar_orcamento'),
    path('remover_cliente/<int:id>', cliente_views.remover_cliente, name='remover_cliente'),
    path('remover_orcamento/<int:id>', orcamento_views.remover_orcamento, name='remover_orcamento'),
    path('cadastrar_orcamento/<int:id>', orcamento_views.inserir_orcamento, name='cadastrar_orcamento'),
    path('lista_orcamentos/<int:id>', orcamento_views.listar_orcamento_id, name='listar_orcamento_id'),
    path('cadastrar_funcionario', funcionario_views.inserir_funcionario, name='cadastrar_funcionario'),
    path('listar_funcionarios', funcionario_views.listar_funcionarios, name='listar_funcionarios'),
    path('login', autenticacao_views.login_usuario, name='login'),
    path('logout', autenticacao_views.deslogar_usuario, name='logout'),
    path('enviar_orcamento/<int:id>', orcamento_views.enviar_email_orcamento, name='enviar_orcamento'),
    path('orcamentos/contagem/', orcamento_views.contagem_orcamentos, name='contagem_todos_orcamentos'),
    path('remover_funcionario/<int:id>', funcionario_views.remover_funcionario, name='remover_funcionario')
    ]

orcamentos/orcamentos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("app/", include('app.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orcamentos/app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django_localflavor_br.br_states import STATE_CHOICES

# Create your models here.

class EnderecoCliente(models.Model):
    rua = models.CharField(max_length=50, null=False, blank=False)
    cidade = models.CharField(max_length=30, null=False, blank=False)
    estado = models.CharField(max_length=2, choices=STATE_CHOICES, null=False, blank=False)

class Cliente(models.Model):
    nome = models.CharField(max_length=100, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    endereco = models.ForeignKey(EnderecoCliente, on_delete=models.CASCADE)
    cpf = models.CharField(max_length=14, null=False, blank=False)
    telefone = models.CharField(max_length=11,null=False, blank=False)
    data_nascimento = models.DateField(null=False, blank=False)
    profissao = models.CharField(max_length=25, null=False, blank=False)

class Orcamento(models.Model):
    forma_pagamento_choices = [
        (1, '1x Cartão de Débito'),
        (2, '2x Cartão de Débito'),
        (3, '3x Cartão de Débito'),
        (4, '4x Cartão de Débito'),
        (5, '5x Cartão de Débito'),
        (6, '6x Cartão de Débito'),
        (7, '1x Cartão de Crédito'),
        (8, '2x Cartão de Crédito'),
        (9, '3x Cartão de Crédito'),
        (10, '4x Cartão de Crédito'),
        (11, '5x Cartão de Crédito'),
        (12, '6x Cartão de Crédito'),
        (13, 'Dinheiro')
    ]

    cirurgias_choices = [
        (1, 'Abdominoplastia'),
        (2, 'Mini-abdominoplastia'),
        (3, 'Blefaroplastia Superior'),
        (4, 'Blefaroplastia Inferior'),
        (5, 'Blefaroplastia Superior e Inferior'),
        (6, 'Braquioplastia'),
        (7, 'Face'),
        (8, 'Lipoaspiração'),
        (9, 'Lipoaspiração de Dorso'),
        (10, 'Lipoaspiração de Submento'),
        (11, 'Mama Redutora'),
        (12, 'Mamoplastia de Aumento'),
        (13, 'Mastopexia'),
        (14, 'Mastopexia com Prótese'),
        (15, 'Ninfoplastia'),
        (16, 'Otoplastia'),
        (17, 'Retoque'),
        (18, 'Rinoplastia'),
        (19, 'Tumores cutâneos')
    ]   

    pac = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=False, blank=False)
    data = models.DateField(null=False, blank=False, auto_now_add=True)
    
    nomeorc = models.CharField(max_length=200, null=False, blank=False)
    descr = models.CharField(max_length=400, null=False, blank=False)

    proc1 = models.IntegerField(choices=cirurgias_choices, null=False, blank=False)
    val1 = models.FloatField(null=True, blank=True)
    pag1 = models.IntegerField(choices=forma_pagamento_choices, null=False, blank=False)

    proc2 = models.IntegerField(choices=cirurgias_choices, null=True, blank=True)
    val2 = models.FloatField(null=True, blank=True)
    pag2 = models.IntegerField(choices=forma_pagamento_choices, null=True, blank=True)

    proc3 = models.IntegerField(choices=cirurgias_choices, null=True, blank=True)
    val3 = models.FloatField(null=True, blank=True)
    pag3 = models.IntegerField(choices=forma_pagamento_choices, null=True, blank=True)

    proc4 = models.IntegerField(choices=cirurgias_choices, null=True, blank=True)
    val4 = models.FloatField(null=True, blank=True)
    pag4 = models.IntegerField(choices=forma_pagamento_choices, null=True, blank=True)

    proc5 = models.IntegerField(choices=cirurgias_choices, null=True, blank=True)
    val5 = models.FloatField(null=True, blank=True)
    pag5 = models.IntegerField(choices=forma_pagamento_choices, null=True, blank=True)

    proc6 = models.IntegerField(choices=cirurgias_choices, null=True, blank=True)
    val6 = models.FloatField(null=True, blank=True)
    pag6 = models.IntegerField(choices=forma_pagamento_choices, null=True, blank=True)

    def total(self):
        return (self.val1 or 0) + (self.val2 or 0) + (self.val3 or 0) + (self.val4 or 0) + (self.val5 or 0) + (self.val6 or 0)

class Funcionario(AbstractUser):
    CARGO_CHOICES = [
        (1, 'Médico'),
        (2, 'Suporte'),
        (3, 'Atendimento'),
    ]
    nome = models.CharField(max_length=50, null=False, blank=False)
    nascimento = models.DateField(null=False, blank=False)
    cargo = models.IntegerField(choices=CARGO_CHOICES, null=False, blank=False)

orcamentos/app/forms/orcamento_forms.py
from django import forms

from ..models import Orcamento


class OrcamentoForm(forms.ModelForm):
    class Meta:
        model = Orcamento
        fields = '__all__'
        exclude = ['pac','data']

orcamentos/app/views/orcamento_views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.template.loader import render_to_string
from django.core.mail import send_mail

from orcamentos import settings

from ..forms.orcamento_forms import OrcamentoForm
from ..entidades import orcamento
from ..services import orcamento_services, cliente_service
from ..views import cliente_views
from ..models import Cliente, Orcamento

@user_passes_test(lambda u: u.cargo==1)
def inserir_orcamento(request, id):
    cliente = cliente_service.listar_cliente_id(id)
    cliente = cliente.id
    if request.method == "POST":
        form_orcamento = OrcamentoForm(request.POST)
        pac = cliente_service.listar_cliente_id(id)
        if form_orcamento.is_valid():
            nomeorc = form_orcamento.cleaned_data["nomeorc"]
            descr = form_orcamento.cleaned_data["descr"]
            proc1 = form_orcamento.cleaned_data["proc1"]
            val1 = form_orcamento.cleaned_data["val1"]
            pag1 = form_orcamento.cleaned_data["pag1"]
            proc2 = form_orcamento.cleaned_data["proc2"]
            val2 = form_orcamento.cleaned_data["val2"]
            pag2 = form_orcamento.cleaned_data["pag2"]
            proc3 = form_orcamento.cleaned_data["proc3"]
            val3 = form_orcamento.cleaned_data["val3"]
            pag3 = form_orcamento.cleaned_data["pag3"]
            proc4 = form_orcamento.cleaned_data["proc4"]
            val4 = form_orcamento.cleaned_data["val4"]
            pag4 = form_orcamento.cleaned_data["pag4"]
            proc5 = form_orcamento.cleaned_data["proc5"]
            val5 = form_orcamento.cleaned_data["val5"]
            pag5 = form_orcamento.cleaned_data["pag5"]
            proc6 = form_orcamento.cleaned_data["proc6"]
            val6 = form_orcamento.cleaned_data["val6"]
            pag6 = form_orcamento.cleaned_data["pag6"]
            orcamento_novo = orcamento.Orcamentos(pac=pac, nomeorc=nomeorc,descr=descr, proc1=proc1, val1=val1, pag1=pag1, proc2=proc2,val2=val2, pag2=pag2, proc3=proc3, val3=val3, pag3=pag3, proc4=proc4, val4=val4, pag4=pag4, proc5=proc5, val5=val5, pag5=pag5, proc6=proc6, val6=val6, pag6=pag6)
            orcamento_services.cadastrar_orcamento(orcamento_novo)
            url = reverse(cliente_views.listar_cliente_id, args=[cliente])
            return redirect(url)
    else:
        form_orcamento = OrcamentoForm()
    return render(request, 'orcamentos/form_orcamento.html', {'form_orcamento': form_orcamento})

@user_passes_test(lambda u: u.cargo==1)
def listar_orcamentos(request):
    orcamentos = orcamento_services.listar_orcamento()
    return render(request, 'orcamentos/lista_orcamentos.html', {'orcamentos': orcamentos})

@user_passes_test(lambda u: u.cargo==1)
def listar_orcamento_id(request, id):
    orcamento = orcamento_services.listar_orcamentos_id(id)
    return render(request, 'orcamentos/lista_orcamentos.html', {'orcamento': orcamento})

@user_passes_test(lambda u: u.cargo==1)
def enviar_email_orcamento(request, id):
    orcamento = orcamento_services.listar_orcamentos_id(id)
    cliente = cliente_service.listar_cliente_id(orcamento.pac.id)
    assunto = "Orçamento"
    html_conteudo = render_to_string('orcamentos/orcamento_email.html', {'orcamento':orcamento})
    corpo_email = "Resumo do Orçamento"
    email_remetente = settings.EMAIL_HOST_USER
    email_destino = [cliente.email,]
    send_mail(assunto, corpo_email, email_remetente, email_destino, html_message=html_conteudo)
    return redirect('listar_orcamento_id', id)

@user_passes_test(lambda u: u.cargo==1)
def remover_orcamento(request, id):
    orcamento = orcamento_services.listar_orcamentos_id(id)
    cliente = orcamento.pac.id
    if request.method == "POST":
        orcamento_services.remover_orcamento(orcamento)
        cliente_id = cliente
        url = reverse(cliente_views.listar_cliente_id, args=[cliente_id])
        return redirect(url)
    return render(request, 'orcamentos/confirma_exclusao_orcamento.html', {'orcamento': orcamento})

@user_passes_test(lambda u: u.cargo==1)
def editar_orcamento(request, id):
    orcamento_editar = orcamento_services.listar_orcamentos_id(id)
    cliente = cliente_service.listar_cliente_id(orcamento_editar.pac.id)
    form_orcamento = OrcamentoForm(request.POST or None, instance=orcamento_editar)
    if form_orcamento.is_valid():
        pac = form_orcamento.cleaned_data["pac"]
        nomeorc = form_orcamento.cleaned_data["nomeorc"]
        descr = form_orcamento.cleaned_data["descr"]
        proc1 = form_orcamento.cleaned_data["proc1"]
        val1 = form_orcamento.cleaned_data["val1"]
        pag1 = form_orcamento.cleaned_data["pag1"]
        proc2 = form_orcamento.cleaned_data["proc2"]
        val2 = form_orcamento.cleaned_data["val2"]
        pag2 = form_orcamento.cleaned_data["pag2"]
        proc3 = form_orcamento.cleaned_data["proc3"]
        val3 = form_orcamento.cleaned_data["val3"]
        pag3 = form_orcamento.cleaned_data["pag3"]
        proc4 = form_orcamento.cleaned_data["proc4"]
        val4 = form_orcamento.cleaned_data["val4"]
        pag4 = form_orcamento.cleaned_data["pag4"]
        proc5 = form_orcamento.cleaned_data["proc5"]
        val5 = form_orcamento.cleaned_data["val5"]
        pag5 = form_orcamento.cleaned_data["pag5"]
        proc6 = form_orcamento.cleaned_data["proc6"]
        val6 = form_orcamento.cleaned_data["val6"]
        pag6 = form_orcamento.cleaned_data["pag6"]
        orcamento_novo = orcamento.Orcamentos(pac=pac, nomeorc=nomeorc, descr=descr, proc1=proc1, val1=val1, pag1=pag1, proc2=proc2, val2=val2, pag2=pag2, proc3=proc3, val3=val3, pag3=pag3, proc4=proc4, val4=val4, pag4=pag4, proc5=proc5, val5=val5, pag5=pag5, proc6=proc6, val6=val6, pag6=pag6)
        orcamento_services.editar_orcamento(orcamento_editar, orcamento_novo)
        return render(request, 'clientes/lista_cliente.html', {'cliente': cliente})
    return render(request, 'orcamentos/form_orcamento.html', {'form_orcamento': form_orcamento})

def contagem_orcamentos(request):
    contagem = orcamento_services.contar_orcamentos_id()
    return render(request, 'orcamentos/contagem_orcamentos.html', {'contagem': contagem})

orcamentos/app/templates/orcamentos/confirma_exclusao_orcamento.html
{% extends 'base.html' %}

{% block title %}
Remoção de Orçamentos
{% endblock title %}

{% block content %}
<style>
    .word-wrap-break {
        word-wrap: break-word;
    }
    button {
        margin-right: 10px;
    }
</style>
<section class="invoice">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">
                <i class="fa fa-trash"></i> Tem certeza que deseja exluir o orçamento a seguir?  
            </h2>
            <h5>Nome da Cirugia: {{orcamento.nomeorc}}</h5>
            <h5>Descrição: <span class="word-wrap-break">{{orcamento.descr}}</span></h5>
            <h5>Data: {{orcamento.data}}</h5>

            <form method="POST">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit">Remover</button>
            </form>
        </div>
    </div>
</section>
{% endblock content %}

orcamentos/app/templates/orcamentos/contagem_orcamentos.html
{% extends 'base.html' %}

{% block title %}
Total de Orçamentos
{% endblock title %}

{% block content %}
<style>
    .word-wrap-break {
        word-wrap: break-word;
    }
    button {
        margin-right: 10px;
    }
</style>
<section class="invoice">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">
                <i class="fa fa-cash"></i>Total de Orçamentos<br>
				Foram encontrados {{ contagem }} orçamentos no banco de dados.
        </div>
    </div>
</section>
{% endblock content %}

orcamentos/app/templates/orcamentos/form_orcamento.html
{% extends "base.html" %}
{% load meus_filtros %}
{% block title %}
Cadastro de Orçamentos
{% endblock title %}

{% block content %}
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Cadastro de Orçamentos</h3>
    </div>
    <div class="box-body">
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        {{ form_orcamentos.nomeorc.errors }}
                        <label>Cirurgia: </label>
                        {{ form_orcamento.nomeorc|addclass:'form-control' }}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        {{ form_orcamentos.descr.errors }}
                        <label>Descrição do Procedimento: </label>
                        {{ form_orcamento.descr|addclass:'form-control' }}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.proc1.errors }}
                        <label>Procedimento 1: </label>
                        {{ form_orcamento.proc1|addclass:'form-control' }}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.val1.errors }}
                        <label>Valor: </label>
                        {{ form_orcamento.val1|addclass:'form-control' }}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.pag1.errors }}
                        <label>Forma de Pagamento: </label>
                        {{ form_orcamento.pag1|addclass:'form-control' }}
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.proc2.errors }}
                        <label>Procedimento 2: </label>
                        {{ form_orcamento.proc2|addclass:'form-control' }}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.val2.errors }}
                        <label>Valor: </label>
                        {{ form_orcamento.val2|addclass:'form-control' }}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.pag2.errors }}
                        <label>Forma de Pagamento: </label>
                        {{ form_orcamento.pag2|addclass:'form-control' }}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.proc3.errors }}
                        <label>Procedimento 3: </label>
                        {{ form_orcamento.proc3|addclass:'form-control' }}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.val3.errors }}
                        <label>Valor: </label>
                        {{ form_orcamento.val3|addclass:'form-control' }}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.pag3.errors }}
                        <label>Forma de Pagamento: </label>
                        {{ form_orcamento.pag3|addclass:'form-control' }}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.proc5.errors }}
                        <label>Serviço 1: </label>
                        <input type="text" name="servico1" value="Hospital" class="form-control" readonly>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.val5.errors }}
                        <label>Valor: </label>
                        {{ form_orcamento.val5|addclass:'form-control' }}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.pag5.errors }}
                        <label>Forma de Pagamento: </label>
                        {{ form_orcamento.pag5|addclass:'form-control' }}
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.proc6.errors }}
                        <label>Serviço 2: </label>
                        <input type="text" name="servico2" value="Equipe" class="form-control" readonly>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.val6.errors }}
                        <label>Valor: </label>
                        {{ form_orcamento.val6|addclass:'form-control' }}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.pag6.errors }}
                        <label>Forma de Pagamento: </label>
                        {{ form_orcamento.pag6|addclass:'form-control' }}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.proc4.errors }}
                        <label>*Serviço 3: </label>
                        <input type="text" name="servico3" value="Implante Mamário" class="form-control" readonly>
                        <div class="rodape">*Fornecido por terceiro</div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.val4.errors }}
                        <label>Valor: </label>
                        {{ form_orcamento.val4|addclass:'form-control' }}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        {{ form_orcamento.pag4.errors }}
                        <label>Forma de Pagamento: </label>
                        {{ form_orcamento.pag4|addclass:'form-control' }}
                    </div>
                </div>

            </div>


            <div class="form-group">
                <input type="submit" name="Cadastrar" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>
{% endblock content %}

orcamentos/app/templates/orcamentos/lista_orcamentos.html
{% extends "base.html" %}
{% load meus_filtros %}
{% block title %}
Orçamento
{% endblock title %}

{% block content %}
<style>
    .invoice-col {
        word-wrap: break-word;
    }
    button {
        margin-right: 10px;
    }
</style>
<section class="invoice">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">
                <i class="fa fa-stethoscope"></i> Orçamento
                
            </h2>
        </div>
    </div>
    
    <div class="row invoice-info">
        <div class="col-lg-12 invoice-col">

            <b>Data:</b> {{orcamento.data}} <br>
            <br>
            <b>Cirurgia: </b> {{orcamento.nomeorc}} <br>
            <br>
            <b>Descrição: </b> {{orcamento.descr}} <br>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-lg-12">
            <b>Procedimentos e Valores:</b>
            <br>
            <b>{{orcamento.get_proc1_display}}:</b> R$ {{orcamento.val1}} - {{orcamento.get_pag1_display}}<br>           
            {% if orcamento.proc2 == null %}
                {{ form.DELETE }}
            {% else %}
                <b>{{orcamento.get_proc2_display}} : </b>R$ {{orcamento.val2}} - {{orcamento.get_pag2_display}}<br>
            {% endif %}
            {% if orcamento.get_proc3 == null %}
                {{ form.DELETE }}
            {% else %}
                <b>R$ {{orcamento.get_proc3_display}} : </b>{{orcamento.val3}} - {{orcamento.get_pag3_display}}<br>
            {% endif %}
            {% if orcamento.val5 == null %}
                {{ form.DELETE }}
            {% else %}
                <b>Hospital: </b>R$ {{orcamento.val5}} - {{orcamento.get_pag5_display}}<br>
            {% endif %}
            {% if orcamento.val6 == null %}
                {{ form.DELETE }}
            {% else %}
                <b>Equipe: </b>R$ {{orcamento.val6}} - {{orcamento.get_pag6_display}}<br>
            {% endif %}
            {% if orcamento.val4 == null %}
                {{ form.DELETE }}
            {% else %}
                <b>*Implante Mamário: </b>R$ {{orcamento.val4}} - {{orcamento.get_pag4_display}}<br>
                <i>*Fornecido por terceiro</i>
            {% endif %}
            <hr>
            <h3><b>Valor total:</b> R$ {{ orcamento.total|floatformat:2 }}</h3>


            <p><i>Válido por 90 dias a partir da data de envio deste orçamento.</i></p>
        </div>
    </div>
    <hr>

    <div class="row no-print">
        <div class="col-xs-12">
            <a href="{% url 'enviar_orcamento' orcamento.id %}">
                <button type="button" class="btn btn-alert pull-left">
                    <i class="fa fa-send"> Enviar por email</i>
                </button>
            </a>
            <button type="button" class="btn btn-primary pull-left" onclick="window.print();">
                <i class="fa fa-print"> Imprimir</i>
            </button>
            <a href="{% url 'remover_orcamento' orcamento.id %}">
                <button type="button" class="btn btn-danger pull-right">
                    <i class="fa fa-trash"> Excluir</i>
                </button>
            </a>
            </a>
        </div>
    </div>

</section>

{% endblock content %}

orcamentos/app/templates/orcamentos/orcamento_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Orçamento</title>
</head>
<body>
    <section class="invoice">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">
                    <i class="fa fa-stethoscope"></i> Orçamento
                    
                </h2>
            </div>
        </div>
        
        <div class="row invoice-info">
            <div class="col-lg-12 invoice-col">
    
                <b>Data:</b> {{orcamento.data}} <br>
                <br>
                <b>Cirurgia: </b> {{orcamento.nomeorc}} <br>
                <br>
                <b>Descrição: </b> {{orcamento.descr}} <br>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-12">
                <b>Procedimentos e Valores:</b>
                <br>
                <b>{{orcamento.get_proc1_display}}:</b> R$ {{orcamento.val1}} - {{orcamento.get_pag1_display}}<br>           
                {% if orcamento.proc2 == null %}
                    {{ form.DELETE }}
                {% else %}
                    <b>{{orcamento.get_proc2_display}} : </b>R$ {{orcamento.val2}} - {{orcamento.get_pag2_display}}<br>
                {% endif %}
                {% if orcamento.get_proc3 == null %}
                    {{ form.DELETE }}
                {% else %}
                    <b>{{orcamento.get_proc3_display}} : </b>R$ {{orcamento.val3}} - {{orcamento.get_pag3_display}}<br>
                {% endif %}
                {% if orcamento.get_proc4 == null %}
                    {{ form.DELETE }}
                {% else %}
                    <b>{{orcamento.get_proc4_display}} : </b>R$ {{orcamento.val4}} - {{orcamento.get_pag4_display}}<br>
                {% endif %}
    
                <b>Hospital : </b>R$ {{orcamento.val5}} - {{orcamento.get_pag5_display}}<br>
    
                <b>Equipe : </b>R$ {{orcamento.val6}} - {{orcamento.get_pag6_display}}<br>
                <hr>
                <h3><b>Valor total:</b> R$ {{ orcamento.total }}</h3>
                <p><i>Válido por 90 dias a partir da data de envio deste orçamento.</i></p>
            </div>
        </div>
        <hr>

</section>      
</body>
</html>