orcamentos/app/urls.py
from django.urls import path
from .views import cliente_views, orcamento_views, funcionario_views, autenticacao_views

urlpatterns = [
    path('cadastrar_cliente', cliente_views.cadastrar_cliente, name='cadastrar_cliente'),
    path('listar_clientes', cliente_views.listar_clientes, name='listar_clientes'),
    path('lista_cliente/<int:id>', cliente_views.listar_cliente_id, name='listar_cliente_id'),
    path('editar_cliente/<int:id>', cliente_views.editar_cliente, name='editar_cliente'),
    path('editar_orcamento/<int:id>', orcamento_views.editar_orcamento, name='editar_orcamento'),
    path('remover_cliente/<int:id>', cliente_views.remover_cliente, name='remover_cliente'),
    path('remover_orcamento/<int:id>', orcamento_views.remover_orcamento, name='remover_orcamento'),
    path('cadastrar_orcamento/<int:id>', orcamento_views.inserir_orcamento, name='cadastrar_orcamento'),
    path('lista_orcamentos/<int:id>', orcamento_views.listar_orcamento_id, name='listar_orcamento_id'),
    path('cadastrar_funcionario', funcionario_views.inserir_funcionario, name='cadastrar_funcionario'),
    path('listar_funcionarios', funcionario_views.listar_funcionarios, name='listar_funcionarios'),
    path('login', autenticacao_views.login_usuario, name='login'),
    path('logout', autenticacao_views.deslogar_usuario, name='logout'),
    path('enviar_orcamento/<int:id>', orcamento_views.enviar_email_orcamento, name='enviar_orcamento'),
    path('orcamentos/contagem/', orcamento_views.contagem_orcamentos, name='contagem_todos_orcamentos'),
    path('remover_funcionario/<int:id>', funcionario_views.remover_funcionario, name='remover_funcionario')
    ]

orcamentos/orcamentos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("app/", include('app.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orcamentos/app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django_localflavor_br.br_states import STATE_CHOICES

# Create your models here.

class EnderecoCliente(models.Model):
    rua = models.CharField(max_length=50, null=False, blank=False)
    cidade = models.CharField(max_length=30, null=False, blank=False)
    estado = models.CharField(max_length=2, choices=STATE_CHOICES, null=False, blank=False)

class Cliente(models.Model):
    nome = models.CharField(max_length=100, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    endereco = models.ForeignKey(EnderecoCliente, on_delete=models.CASCADE)
    cpf = models.CharField(max_length=14, null=False, blank=False)
    telefone = models.CharField(max_length=11,null=False, blank=False)
    data_nascimento = models.DateField(null=False, blank=False)
    profissao = models.CharField(max_length=25, null=False, blank=False)

class Orcamento(models.Model):
    forma_pagamento_choices = [
        (1, '1x Cartão de Débito'),
        (2, '2x Cartão de Débito'),
        (3, '3x Cartão de Débito'),
        (4, '4x Cartão de Débito'),
        (5, '5x Cartão de Débito'),
        (6, '6x Cartão de Débito'),
        (7, '1x Cartão de Crédito'),
        (8, '2x Cartão de Crédito'),
        (9, '3x Cartão de Crédito'),
        (10, '4x Cartão de Crédito'),
        (11, '5x Cartão de Crédito'),
        (12, '6x Cartão de Crédito'),
        (13, 'Dinheiro')
    ]

    cirurgias_choices = [
        (1, 'Abdominoplastia'),
        (2, 'Mini-abdominoplastia'),
        (3, 'Blefaroplastia Superior'),
        (4, 'Blefaroplastia Inferior'),
        (5, 'Blefaroplastia Superior e Inferior'),
        (6, 'Braquioplastia'),
        (7, 'Face'),
        (8, 'Lipoaspiração'),
        (9, 'Lipoaspiração de Dorso'),
        (10, 'Lipoaspiração de Submento'),
        (11, 'Mama Redutora'),
        (12, 'Mamoplastia de Aumento'),
        (13, 'Mastopexia'),
        (14, 'Mastopexia com Prótese'),
        (15, 'Ninfoplastia'),
        (16, 'Otoplastia'),
        (17, 'Retoque'),
        (18, 'Rinoplastia'),
        (19, 'Tumores cutâneos')
    ]   

    pac = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=False, blank=False)
    data = models.DateField(null=False, blank=False, auto_now_add=True)
    
    nomeorc = models.CharField(max_length=200, null=False, blank=False)
    descr = models.CharField(max_length=400, null=False, blank=False)

    proc1 = models.IntegerField(choices=cirurgias_choices, null=False, blank=False)
    val1 = models.FloatField(null=True, blank=True)
    pag1 = models.IntegerField(choices=forma_pagamento_choices, null=False, blank=False)

    proc2 = models.IntegerField(choices=cirurgias_choices, null=True, blank=True)
    val2 = models.FloatField(null=True, blank=True)
    pag2 = models.IntegerField(choices=forma_pagamento_choices, null=True, blank=True)

    proc3 = models.IntegerField(choices=cirurgias_choices, null=True, blank=True)
    val3 = models.FloatField(null=True, blank=True)
    pag3 = models.IntegerField(choices=forma_pagamento_choices, null=True, blank=True)

    proc4 = models.IntegerField(choices=cirurgias_choices, null=True, blank=True)
    val4 = models.FloatField(null=True, blank=True)
    pag4 = models.IntegerField(choices=forma_pagamento_choices, null=True, blank=True)

    proc5 = models.IntegerField(choices=cirurgias_choices, null=True, blank=True)
    val5 = models.FloatField(null=True, blank=True)
    pag5 = models.IntegerField(choices=forma_pagamento_choices, null=True, blank=True)

    proc6 = models.IntegerField(choices=cirurgias_choices, null=True, blank=True)
    val6 = models.FloatField(null=True, blank=True)
    pag6 = models.IntegerField(choices=forma_pagamento_choices, null=True, blank=True)

    def total(self):
        return (self.val1 or 0) + (self.val2 or 0) + (self.val3 or 0) + (self.val4 or 0) + (self.val5 or 0) + (self.val6 or 0)

class Funcionario(AbstractUser):
    CARGO_CHOICES = [
        (1, 'Médico'),
        (2, 'Suporte'),
        (3, 'Atendimento'),
    ]
    nome = models.CharField(max_length=50, null=False, blank=False)
    nascimento = models.DateField(null=False, blank=False)
    cargo = models.IntegerField(choices=CARGO_CHOICES, null=False, blank=False)

orcamentos/app/forms/funcionario_forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import DateInput

from ..models import Funcionario


class FuncionarioForm(UserCreationForm):
    class Meta:
        model = Funcionario
        fields = UserCreationForm.Meta.fields + ('nome', 'nascimento', 'cargo')
        widgets = {
            'nascimento': DateInput(
                attrs={'type': "date"}
            )
        }

orcamentos/app/views/funcionario_views.py
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import make_password
from django.shortcuts import render, redirect
from ..forms.funcionario_forms import FuncionarioForm
from ..entidades import funcionario
from ..services import funcionario_service
from ..views import funcionario_views
from django.urls import reverse


def listar_funcionarios(request):
    funcionarios = funcionario_service.listar_funcionarios()
    return render(request, 'funcionarios/lista_funcionarios.html', {'funcionarios': funcionarios})

@user_passes_test(lambda u: u.cargo==1)
def listar_funcionarios_id(request, id):
    funcionarios = funcionario_service.listar_funcionarios_id(id)
    return render(request, 'funcionarios/lista_funcionarios.html', {'funcionario': funcionarios})

@user_passes_test(lambda u: u.cargo==1)
def inserir_funcionario(request):
    if request.method == "POST":
        form_funcionario = FuncionarioForm(request.POST)
        if form_funcionario.is_valid():
            nome = form_funcionario.cleaned_data["nome"]
            nascimento = form_funcionario.cleaned_data["nascimento"]
            cargo = form_funcionario.cleaned_data["cargo"]
            username = form_funcionario.cleaned_data["username"]
            password = make_password(form_funcionario.cleaned_data["password1"])
            funcionario_novo = funcionario.Funcionario(nome=nome, nascimento=nascimento, cargo=cargo, username=username, password=password)
            funcionario_service.cadastrar_funcionario(funcionario_novo)
            return redirect('listar_funcionarios')
    else:
        form_funcionario = FuncionarioForm()
    return render(request, 'funcionarios/form_funcionario.html', {'form_funcionario': form_funcionario})

@user_passes_test(lambda u: u.cargo==1)
def remover_funcionario(request, id):
    funcionario = funcionario_service.listar_funcionarios_id(id)
    if request.method == "POST":
        funcionario_service.remover_funcionario(funcionario)
        return redirect(listar_funcionarios)
    return render(request, 'funcionarios/confirma_exclusao_funcionario.html', {'funcionario': funcionario})

orcamentos/app/templates/funcionarios/confirma_exclusao_funcionario.html
{% extends 'base.html' %}

{% block title %}
Remoção de Funcionários
{% endblock title %}

{% block content %}
<style>
    .word-wrap-break {
        word-wrap: break-word;
    }
    button {
        margin-right: 10px;
    }
</style>
<section class="invoice">
    <div class="row">
        <div class="col-lg-12">
            <h2 class="page-header">
                <i class="fa fa-trash"></i> Tem certeza que deseja exluir o funcionário a seguir?  
            </h2>
            <h5>Nome: {{funcionario.nome}}</h5>

            <form method="POST">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit">Remover</button>
            </form>
        </div>
    </div>
</section>
{% endblock content %}

orcamentos/app/templates/funcionarios/form_funcionario.html
{% extends "base.html" %}
{% load meus_filtros %}
{% block title %}
Cadastro de funcionários
{% endblock title %}

{% block content %}
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Cadastro de funcionários</h3>
    </div>
    <div class="box-body">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form_funcionario.nome.errors }}
                <label>Nome: </label>
                {{ form_funcionario.nome|addclass:'form-control' }}

            </div>

            <div class="form-group">
                {{ form_funcionario.nascimento.errors }}
                <label>Data de nascimento: </label>
                {{ form_funcionario.nascimento|addclass:'form-control' }}
            </div>

            <div class="form-group">
                {{ form_funcionario.cargo.errors }}
                <label>Cargo: </label>
                {{ form_funcionario.cargo|addclass:'form-control' }}
            </div>

            <div class="form-group">
                {{ form_funcionario.username.errors }}
                <label>Usuário: </label>
                {{ form_funcionario.username|addclass:'form-control' }}
            </div>

            <div class="form-group">
                {{ form_funcionario.password1.errors }}
                <label>Senha: </label>
                {{ form_funcionario.password1|addclass:'form-control' }}
            </div>

            <div class="form-group">
                {{ form_funcionario.password2.errors }}
                <label>Confirme sua senha: </label>
                {{ form_funcionario.password2|addclass:'form-control' }}
            </div>

            <div class="form-group">
                <input type="submit" name="Cadastrar" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>
{% endblock content %}

orcamentos/app/templates/funcionarios/lista_funcionarios.html
{% extends "base.html" %}

{% block title %}
Listagem de clientes
{% endblock title %}

{% block content %}
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">Listagem de funcionários</h3>
    </div>
    <div class="box-body">
        <table class="table">
            <thead>
            <tr>
                <th>Nome</th>
                <th>Data de Nascimento</th>
                <th>Cargo</th>
                <th>Nome do Usuário</th>
            </tr>
            </thead>
            <tbody>
            {% for i in funcionarios %}
            <tr>
                <td>{{i.nome}}</td>
                <td>{{i.nascimento}}</td>
                <td>{{i.get_cargo_display}}</td>
                <td>{{i.username}}</td>
                <td>
                    <a href="{% url 'remover_funcionario' i.id %}">Remover</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <hr>

        <a href="{% url 'cadastrar_funcionario' %}">
            <button class="btn btn-primary">Cadastrar</button>
        </a>
    </div>
</div>
{% endblock content %}